apiVersion: v1
kind: Namespace
metadata:
  name: Microsoft
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: Microsoft
spec:
  limits: 
   - default: 
        memory: "512Mi"
        cpu: "500m"
     defaultRequest:
        memory: "256Mi"
        cpu: "250m"
     type: Container